name: Deploy Website 2

on:
  push:
    branches: [ main ]
    paths:
      - 'website 2/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: "./website 2"
        file: "./website 2/Dockerfile"
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/coffee-quality-website2:latest
          ${{ secrets.DOCKER_USERNAME }}/coffee-quality-website2:${{ github.sha }}
